// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Import the generated API sidebar
import apiSidebar from './docs/api/sidebar';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  adminGuideSidebar: [{type: 'autogenerated', dirName: 'admin-guide'}],
  developerDocsSidebar: [{type: 'autogenerated', dirName: 'developer-docs'}],
  apiSidebar: [
    {
      type: 'category',
      label: 'Conducky API',
      link: {
        type: 'generated-index',
        title: 'Conducky API',
        description: 'API documentation for the Conducky platform',
        slug: '/api',
      },
      items: apiSidebar,
    },
  ],
};

export default sidebars;
